apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: vault-app
  labels:
    app: vault-app
    container: mongodb
spec:
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: vault-app
    container: mongodb
  type: ClusterIP
  sessionAffinity: None


---
kind: Secret
apiVersion: v1
metadata:
  name: mongodb
  namespace: vault-app
  labels:
    app: vault-app
data:
  MONGODB_ROOT_PASSWORD: YWRtaW5wYXNzc3dvcmQ=
  MONGODB_DATABASE: c2FtcGxlZGI=
  MONGODB_PASSWORD: cGFzc3dvcmQ=
  MONGODB_USERNAME: YWRtaW4=
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: vault-app
  labels:
    app: vault-app
    container: mongodb
spec:
  replicas: 1
  serviceName: "mongodb"
  selector:
    matchLabels:
      app: vault-app
      container: mongodb
  template:
    metadata:
      namespace: vault-app
      labels:
        app: vault-app
        container: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.access.redhat.com/rhscl/mongodb-32-rhel7
        volumeMounts:
        - name: mongodb-data
          mountPath: /var/lib/mongodb/data
        ports:
        - containerPort: 27017
          protocol: TCP
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: MONGODB_PASSWORD
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: MONGODB_ROOT_PASSWORD
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: MONGODB_DATABASE
        readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval="quit()"
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
      - name: mongodb-data
        emptyDir: {}
      - name: app-config
        emptyDir: {}
      imagePullPolicy: IfNotPresent